# SELECT COUNT(*) AS FISH_COUNT FROM FISH_INFO A, FISH_NAME_INFO B
# WHERE A.FISH_TYPE = B.FISH_TYPE AND B.FISH_NAME IN ('BASS', 'SNAPPER')
SELECT COUNT(*) AS FISH_COUNT 
FROM FISH_INFO A JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
WHERE B.FISH_NAME IN ('BASS', 'SNAPPER')